version: "3"
services:
  web-echo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "8080"
    environment:
        # domain and https

      - DB_DSN=${DB_DSN}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

networks:
  default:
    external: true
    name: ${NETWORK_NAME}
